lib: [
  "/Users/ostera/.esy/3__________________________________________________________________/b/cactus-f1123225/install/default/lib/cactus/META" {"META"}
  "/Users/ostera/.esy/3__________________________________________________________________/b/cactus-f1123225/install/default/lib/cactus/dune-package" {"dune-package"}
  "/Users/ostera/.esy/3__________________________________________________________________/b/cactus-f1123225/install/default/lib/cactus/opam" {"opam"}
]
bin: [
  "/Users/ostera/.esy/3__________________________________________________________________/b/cactus-f1123225/install/default/bin/cactus" {"cactus"}
]
doc: [
  "/Users/ostera/.esy/3__________________________________________________________________/b/cactus-f1123225/install/default/doc/cactus/README.md"
]
