lib: [
  "/Users/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-643a08d8/install/default/lib/cactus/META" {"META"}
  "/Users/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-643a08d8/install/default/lib/cactus/opam" {"opam"}
]
bin: [
  "/Users/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-643a08d8/install/default/bin/cactus" {"cactus"}
]
doc: [
  "/Users/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-643a08d8/install/default/doc/cactus/README.md"
]
