lib: [
  "/home/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-59fb1e15/install/default/lib/cactus/META" {"META"}
  "/home/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-59fb1e15/install/default/lib/cactus/dune-package" {"dune-package"}
  "/home/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-59fb1e15/install/default/lib/cactus/opam" {"opam"}
]
bin: [
  "/home/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-59fb1e15/install/default/bin/cactus" {"cactus"}
]
doc: [
  "/home/ostera/repos/github.com/ostera/cactus/_esy/default/store/b/cactus-59fb1e15/install/default/doc/cactus/README.md"
]
